class AM2 {
  static final _am2UnicodeRules = [
    {"from": "1\u20442", "to": "ရ"},
    {"from": "3\u20444", "to": "္ဂ"},
    {"from": "]]", "to": "\u201c"},
    {"from": "}}", "to": "\u201d"},
    {"from": " ̈", "to": "္ဓ"},
    {"from": "1e", "to": "ဍ္ဎန"},
    {"from": "t H", "to": "အံ"},
    {"from": "a", "to": "ေ"},
    {"from": "b", "to": "ဘ"},
    {"from": "c", "to": "ခ"},
    {"from": "d", "to": "ိ"},
    {"from": "e", "to": "န"},
    {"from": "f", "to": "်"},
    {"from": "g", "to": "ါ"},
    {"from": "h", "to": "့"},
    {"from": "i", "to": "င"},
    {"from": "j", "to": "ြ"},
    {"from": "k", "to": "ု"},
    {"from": "l", "to": "ူ"},
    {"from": "m", "to": "ာ"},
    {"from": "n", "to": "ည"},
    {"from": "o", "to": "သ"},
    {"from": "p", "to": "စ"},
    {"from": "q", "to": "ဆ"},
    {"from": "r", "to": "မ"},
    {"from": "s", "to": "ျ"},
    {"from": "t", "to": "အ"},
    {"from": "u", "to": "က"},
    {"from": "v", "to": "လ"},
    {"from": "w", "to": "တ"},
    {"from": "x", "to": "ထ"},
    {"from": "y", "to": "ပ"},
    {"from": "z", "to": "ဖ"},
    {"from": "0", "to": "၀"},
    {"from": "1", "to": "၁"},
    {"from": "2", "to": "၂"},
    {"from": "3", "to": "၃"},
    {"from": "4", "to": "၄"},
    {"from": "5", "to": "၅"},
    {"from": "6", "to": "၆"},
    {"from": "7", "to": "၇"},
    {"from": "8", "to": "၈"},
    {"from": "9", "to": "၉"},
    {"from": "!", "to": "ဍ"},
    {"from": "\"", "to": "ဓ"},
    {"from": "#", "to": "ဋ"},
    {"from": "\$", "to": "ြွ"},
    {"from": "&", "to": "ရ"},
    {"from": "'", "to": "ဒ"},
    {"from": "*", "to": "ဂ"},
    {"from": ",", "to": "ယ"},
    {"from": ".", "to": "ႏ"},
    {"from": "/", "to": "။"},
    {"from": ":", "to": "ါ်"},
    {"from": ";", "to": "း"},
    {"from": "<", "to": "ြွ"},
    {"from": ">", "to": "ꩻ"},
    {"from": "?", "to": "၊"},
    {"from": "@", "to": "ဏ္ဍ"},
    {"from": "A", "to": "ဗ"},
    {"from": "B", "to": "ြ"},
    {"from": "C", "to": "ဃ"},
    {"from": "D", "to": "ီ"},
    {"from": "E", "to": "န"},
    {"from": "F", "to": "င်္"},
    {"from": "G", "to": "ွ"},
    {"from": "H", "to": "ံ"},
    {"from": "I", "to": "ှု"},
    {"from": "J", "to": "ဲ"},
    {"from": "K", "to": "ု"},
    {"from": "L", "to": "ူ"},
    {"from": "M", "to": "ြ"},
    {"from": "N", "to": "ြ"},
    {"from": "O", "to": "ဥ"},
    {"from": "P", "to": "ဏ"},
    {"from": "Q", "to": "ျှ"},
    {"from": "R", "to": "ျွ"},
    {"from": "S", "to": "ှ"},
    {"from": "T", "to": "ွှ"},
    {"from": "U", "to": "့"},
    {"from": "V", "to": "ဠ"},
    {"from": "W", "to": "ျွှ"},
    {"from": "X", "to": "ဌ"},
    {"from": "Y", "to": "့"},
    {"from": "Z", "to": "ဇ"},
    {"from": "[", "to": "ဟ"},
    {"from": "\\", "to": "၏"},
    {"from": "]", "to": "\u2018"},
    {"from": "^", "to": "/"},
    {"from": "`", "to": "ြ"},
    {"from": "_", "to": "x"},
    {"from": "{", "to": "ဧ"},
    {"from": "|", "to": "ဋ္ဌ"},
    {"from": "}", "to": "'"},
    {"from": "~", "to": "ြ"},
    {"from": "¡", "to": "ဎ"},
    {"from": "¢", "to": "္ဃ"},
    {"from": "£", "to": "ဣ"},
    {"from": "¤", "to": "၎"},
    {"from": "¥", "to": "ဋ္ဋ"},
    {"from": "¦", "to": "္ထ"},
    {"from": "§", "to": "ှ"},
    {"from": "¨", "to": "္ဓ"},
    {"from": "©", "to": "္ခ"},
    {"from": "ª", "to": "ှူ"},
    {"from": "«", "to": "["},
    {"from": "¬", "to": "္ထ"},
    {"from": "®", "to": "္မ"},
    {"from": "°", "to": "မ္ပ"},
    {"from": "±", "to": "ဗ္ဘ"},
    {"from": "²", "to": "္ဌ"},
    {"from": "³", "to": "္ဋ"},
    {"from": "´", "to": "္ဒ"},
    {"from": "µ", "to": "§"},
    {"from": "¶", "to": "ႏ"},
    {"from": "¸", "to": "န္န"},
    {"from": "¹", "to": "ဍ္ဎ"},
    {"from": "º", "to": "ဏ္ဌ"},
    {"from": "»", "to": "]"},
    {"from": "¼", "to": "ဋ"},
    {"from": "½", "to": "ရ"},
    {"from": "¾", "to": "္ဂ"},
    {"from": "¿", "to": "?"},
    {"from": "À", "to": "♦"},
    {"from": "Á", "to": "္ဗ"},
    {"from": "Â", "to": "✓"},
    {"from": "Ã", "to": "♣"},
    {"from": "Ä", "to": "*"},
    {"from": "Å", "to": "္တ"},
    {"from": "Æ", "to": "္ဇ"},
    {"from": "Ç", "to": "္ဘ"},
    {"from": "È", "to": "န္ဓ"},
    {"from": "É", "to": "န္တွ"},
    {"from": "Ê", "to": "\u201c"},
    {"from": "Ë", "to": "ဏ္ဍ"},
    {"from": "Ì", "to": "ဏ္ဋ"},
    {"from": "Í", "to": "ဉ"},
    {"from": "Î", "to": "ြှ"},
    {"from": "Ï", "to": "န္ဒြ"},
    {"from": "Ð", "to": "င်္ီ"},
    {"from": "Ñ", "to": "္စျ"},
    {"from": "Ò", "to": "လ္လ"},
    {"from": "Ó", "to": "ဉာ"},
    {"from": "Ô", "to": "ျွ"},
    {"from": "Õ", "to": "ဉ္စ"},
    {"from": "Ö", "to": "္ဏ"},
    {"from": "×", "to": "ဍ္ဍ"},
    {"from": "Ø", "to": "င်္ိ"},
    {"from": "Ù", "to": "ဉ္ဇ"},
    {"from": "Ú", "to": "ဉ"},
    {"from": "Û", "to": "တ္ထ"},
    {"from": "Ü", "to": "္ပ"},
    {"from": "Ý", "to": "ပ္ပ"},
    {"from": "Þ", "to": "တ္တ"},
    {"from": "ß", "to": "ျ"},
    {"from": "à", "to": "ဗ္ဗ"},
    {"from": "á", "to": "►"},
    {"from": "â", "to": "x"},
    {"from": "ã", "to": "မြို့"},
    {"from": "ä", "to": "္ဆ"},
    {"from": "å", "to": "္တ"},
    {"from": "æ", "to": "္ဖ"},
    {"from": "ç", "to": "ꩻ"},
    {"from": "è", "to": "_"},
    {"from": "é", "to": "္န"},
    {"from": "ê", "to": "ြု"},
    {"from": "ë", "to": "ဲ"},
    {"from": "ì", "to": "ဉှ"},
    {"from": "í", "to": "၍"},
    {"from": "î", "to": "ဉှ"},
    {"from": "ï", "to": "ဠှ"},
    {"from": "ð", "to": "ိံ"},
    {"from": "ñ", "to": "ည"},
    {"from": "ò", "to": "ဒ္ဓ"},
    {"from": "ó", "to": "ဿ"},
    {"from": "ô", "to": "ဒ္ဒ"},
    {"from": "õ", "to": "စ္စ"},
    {"from": "ö", "to": "္စ"},
    {"from": "÷", "to": "÷"},
    {"from": "ø", "to": "င်္ံ"},
    {"from": "ù", "to": "န္ဒ"},
    {"from": "ú", "to": "္က"},
    {"from": "û", "to": "ြု"},
    {"from": "ü", "to": "၌"},
    {"from": "ý", "to": "န္ဇ"},
    {"from": "þ", "to": "ဤ"},
    {"from": "ÿ", "to": "မ္မ"},
    {"from": "Œ", "to": "☆"},
    {"from": "œ", "to": "..."},
    {"from": "Š", "to": "္ဘ"},
    {"from": "š", "to": "္တ"},
    {"from": "Ÿ", "to": "္ပ"},
    {"from": "ƒ", "to": "၍"},
    {"from": "ˆ", "to": "★"},
    {"from": "¯", "to": "ဦ"},
    {"from": "˜", "to": "★"},
    {"from": "\u2014", "to": "✓"},
    {"from": "\u2018", "to": "ဇ္ဇ"},
    {"from": "\u2019", "to": "က္ခ"},
    {"from": "\u201a", "to": "_"},
    {"from": "\u201e", "to": "✓"},
    {"from": "\u2020", "to": "က္က"},
    {"from": "\u2021", "to": "ဂ္ဃ"},
    {"from": "\u2026", "to": "္ဗ"},
    {"from": "\u2030", "to": "န္ဒ"},
    {"from": "\u2039", "to": "ဏ္ဋ"},
    {"from": "\u203a", "to": "န္တ"},
    {"from": "™", "to": "ဉ္စ"},
    {"from": "−", "to": "န္တ"},
    {"from": "·", "to": "ႏ"},
    {"from": "♦", "to": "န္တွ"},
    {"from": "♪", "to": "ဦ"},
    {"from": "♫", "to": "★"},
    {"from": "ﬂ", "to": "!"},
    {"from": " ́", "to": "္ဒ"}
  ];

  static final _reorderUnicodeRules = [
    {"from": "(ံ)(ု)?(ူ)?", "to": "#2#3#1"},
    {"from": "(ိ|ီ)(ွ)", "to": "#2#1"},
    {"from": "(ြ)(၇)", "to": "ြရ"},
    {"from": "(ြ)(၀)", "to": "ြဝ"},
    {"from": "(ြ)([က-အ])", "to": "#2#1"},
    {"from": "(ြ)(ွ)([က-အ])", "to": "#3#1#2"},
    {"from": "([က-အဿ])(င်္)", "to": "#2#1"},
    {"from": "(ု)?(ူ)?(ိ)?(ီ)?", "to": "#3#4#1#2"},
    {"from": "(ဲ)?(ူ)?(ု)?(ျ)?(ြ)?", "to": "#2#3#4#5#1"},
    {"from": "၀(ိ|ီ|ု|ူ|ံ|့|ှ|်|း|ါ|ာ|[က-အ]်|ျ|ဲ|ႏ|ꩻ|ွ)", "to": "ဝ#1"},
    {"from": "၇(ိ|ီ|ု|ူ|ံ|့|ှ|်|း|ါ|ာ|[က-အ]်|ျ|ဲ|ႏ|ꩻ|ွ)", "to": "ရ#1"},
    {"from": "(ေ)(၇)", "to": "ေရ"},
    {"from": "(ေ)(၀)", "to": "ေဝ"},
    {
      "from": "(ေ)(ြ)?([က-အဿ])(ြ)?(ွ)?(ျ)?(ွ)?(ု)?(ှ)?",
      "to": "#3#2#4#6#5#7#1#8#9"
    },
    {"from": "([က-အ])(ေ)(္[က-အ])", "to": "#1#3#2"}
  ];

  static String _transform(String am2) {
    for (var item in _am2UnicodeRules) {
      final from = item["from"]!;
      final to = item["to"]!;
      am2 = am2.replaceAll(from, to);
    }
    return am2;
  }

  static String _reorderUnicode(String input) {
    for (var item in _reorderUnicodeRules) {
      final from = item["from"]!;
      final to = item["to"]!;
      input = input.replaceAllMapped(RegExp(from), (match1) {
        return to.replaceAllMapped(RegExp(r"#(\d)"), (match2) {
          final index = match2.group(1);
          var t = index != null ? match1.group(int.parse(index)) : null;
          return t ?? "";
        });
      });
    }
    return input;
  }

  static String convert(String am2Text) {
    final data = _transform(am2Text);
    return _reorderUnicode(data);
  }
}
